name: Release

on:
  push:
    branches: main
    
  workflow_dispatch:
  
# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          cd scripts
          chmod +x ./build.sh
          ./build.sh
          cd ..
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: Resource compilations (${{ github.ref_name }})
          body: |
            ZIPs of the resources.
            Some subjects may be split into year 11 and year 12 due to the 2 GB release file limit on GitHub.
          files: |
            build/*
          token: ${{ secrets.token }}
